import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import SideBarNavigator from "@/components/ui/SideBarNavigator";
import QueryProvider from "@/components/providers/queryProvider";
import ThemeToaster from "@/components/ui/ThemeToaster";
import StoreProvider from "@/components/providers/StoreProvider";
import SetUser from "@/components/templates/SetUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <StoreProvider>
            <QueryProvider>
              <SidebarProvider>
                <SideBarNavigator />
                <main className="w-screen h-svh">
                  <SidebarTrigger />
                  {children}
                  <ThemeToaster />
                  <SetUser />
                </main>
              </SidebarProvider>
            </QueryProvider>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
